<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.sonarsource.sonarlint.eclipse</groupId>
    <artifactId>sonarlint-eclipse-parent</artifactId>
    <version>12.6.7701</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>org.sonarlint.eclipse.core</artifactId>
  <packaging>eclipse-plugin</packaging>

  <name>SonarLint for Eclipse Core</name>

  <build>
    <sourceDirectory>src</sourceDirectory>

    <resources>
      <resource>
        <directory>${basedir}/src</directory>
        <includes>
          <include>**/*.properties</include>
        </includes>
      </resource>
    </resources>

    <plugins>
      <plugin>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>${os.version}</version>
        <executions>
          <execution>
            <phase>initialize</phase>
            <goals>
              <goal>detect</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
        <configuration>
          <filesets>
            <fileset>
              <directory>${project.basedir}/plugins</directory>
              <includes>
                <include>*.jar</include>
              </includes>
            </fileset>
            <fileset>
              <directory>${project.basedir}/lib</directory>
              <includes>
                <include>*.jar</include>
              </includes>
            </fileset>
          </filesets>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-analyzers</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>eu.rssw.sonar.openedge</groupId>
                  <artifactId>sonar-openedge-plugin</artifactId>
                  <version>3.10.0</version>
                  <type>jar</type>
                </artifactItem>
                <artifactItem>
                  <groupId>eu.rssw.sonar.openedge</groupId>
                  <artifactId>progress-rules-plugin</artifactId>
                  <version>3.10.0</version>
                  <type>jar</type>
                </artifactItem>
                <artifactItem>
                  <groupId>org.sonarsource.text</groupId>
                  <artifactId>sonar-text-plugin</artifactId>
                  <version>2.45.0.11557</version>
                  <type>jar</type>
                </artifactItem>
              </artifactItems>
              <outputDirectory>${project.basedir}/plugins</outputDirectory>
              <overWriteReleases>false</overWriteReleases>
              <overWriteSnapshots>true</overWriteSnapshots>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
